/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DownloadTaskService } from "../downloadTask.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DownloadTaskCreateInput } from "./DownloadTaskCreateInput";
import { DownloadTask } from "./DownloadTask";
import { DownloadTaskFindManyArgs } from "./DownloadTaskFindManyArgs";
import { DownloadTaskWhereUniqueInput } from "./DownloadTaskWhereUniqueInput";
import { DownloadTaskUpdateInput } from "./DownloadTaskUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DownloadTaskControllerBase {
  constructor(
    protected readonly service: DownloadTaskService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DownloadTask })
  @nestAccessControl.UseRoles({
    resource: "DownloadTask",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDownloadTask(
    @common.Body() data: DownloadTaskCreateInput
  ): Promise<DownloadTask> {
    return await this.service.createDownloadTask({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        videoUrl: true,
        status: true,
        progress: true,
        result: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DownloadTask] })
  @ApiNestedQuery(DownloadTaskFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DownloadTask",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async downloadTasks(@common.Req() request: Request): Promise<DownloadTask[]> {
    const args = plainToClass(DownloadTaskFindManyArgs, request.query);
    return this.service.downloadTasks({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        videoUrl: true,
        status: true,
        progress: true,
        result: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DownloadTask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadTask",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async downloadTask(
    @common.Param() params: DownloadTaskWhereUniqueInput
  ): Promise<DownloadTask | null> {
    const result = await this.service.downloadTask({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        videoUrl: true,
        status: true,
        progress: true,
        result: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DownloadTask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadTask",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDownloadTask(
    @common.Param() params: DownloadTaskWhereUniqueInput,
    @common.Body() data: DownloadTaskUpdateInput
  ): Promise<DownloadTask | null> {
    try {
      return await this.service.updateDownloadTask({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          videoUrl: true,
          status: true,
          progress: true,
          result: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DownloadTask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadTask",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDownloadTask(
    @common.Param() params: DownloadTaskWhereUniqueInput
  ): Promise<DownloadTask | null> {
    try {
      return await this.service.deleteDownloadTask({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          videoUrl: true,
          status: true,
          progress: true,
          result: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
